services:
  - type: web
    name: aime-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn aimesite.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: aimesite.settings
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true

autoDeploy: true
