# Generated by Django 4.2.14 on 2025-12-10 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('category', models.CharField(choices=[('news', 'Actualité'), ('event', 'Événement'), ('announcement', 'Annonce'), ('success_story', 'Témoignage'), ('program', 'Programme')], default='news', max_length=20, verbose_name='Catégorie')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='daily_info/', verbose_name='Image (optionnelle)')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('display_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'affichage")),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
                ('link_text', models.CharField(blank=True, default='En savoir plus →', max_length=100, verbose_name='Texte du lien')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Épinglé (priorité d'affichage)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information du Jour',
                'verbose_name_plural': 'Informations du Jour',
                'ordering': ['-is_featured', '-display_date', '-order'],
                'indexes': [models.Index(fields=['is_published', 'display_date'], name='main_dailyi_is_publ_bb0b3a_idx'), models.Index(fields=['is_featured', 'order'], name='main_dailyi_is_feat_699a4c_idx')],
            },
        ),
    ]
