# Generated by Django 4.2.14 on 2026-06-06 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_dailyinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Accueil"),
                            ("about", "À propos"),
                            ("projects", "Nos Projets"),
                            ("events", "Événements"),
                            ("contact", "Contact"),
                            ("donate", "Faire un don"),
                            ("mbc", "Mutoto Bike Challenge"),
                            ("msa", "Mutoto Science Adventure"),
                            ("mon_beau_metier", "Mon Beau Métier"),
                            ("manifesto", "Manifeste"),
                            ("impact_theory", "Théorie du Changement"),
                            ("observatory", "Observatoire des Droits"),
                            ("research_center", "Centre de Recherche"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Page",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Petit label (au-dessus du titre)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre principal"),
                ),
                (
                    "title_highlight",
                    models.CharField(
                        blank=True,
                        help_text="Mot/groupe affiché en couleur accent (optionnel).",
                        max_length=100,
                        verbose_name="Mot mis en évidence",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, verbose_name="Sous-titre / description"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="heroes/",
                        verbose_name="Image de fond",
                    ),
                ),
                (
                    "cta_primary_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Bouton 1 — texte"
                    ),
                ),
                (
                    "cta_primary_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Bouton 1 — lien"
                    ),
                ),
                (
                    "cta_secondary_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Bouton 2 — texte"
                    ),
                ),
                (
                    "cta_secondary_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Bouton 2 — lien"
                    ),
                ),
                (
                    "overlay_enabled",
                    models.BooleanField(default=True, verbose_name="Activer l'overlay"),
                ),
                (
                    "overlay_type",
                    models.CharField(
                        choices=[
                            ("solid", "Couleur unie"),
                            ("linear", "Dégradé linéaire"),
                            ("radial", "Dégradé radial"),
                        ],
                        default="linear",
                        max_length=10,
                        verbose_name="Type d'overlay",
                    ),
                ),
                (
                    "overlay_color",
                    models.CharField(
                        default="#0A2A4D", max_length=7, verbose_name="Couleur overlay"
                    ),
                ),
                (
                    "overlay_color_2",
                    models.CharField(
                        blank=True,
                        help_text="Utilisée pour les dégradés. Laisser vide = même couleur.",
                        max_length=7,
                        verbose_name="2e couleur (dégradé)",
                    ),
                ),
                (
                    "overlay_opacity",
                    models.PositiveIntegerField(
                        default=55,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Opacité (%)",
                    ),
                ),
                (
                    "overlay_angle",
                    models.PositiveIntegerField(
                        default=135,
                        validators=[django.core.validators.MaxValueValidator(360)],
                        verbose_name="Angle dégradé (deg)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section Hero",
                "verbose_name_plural": "Sections Hero",
                "ordering": ["page"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@aime-rdc.org",
                        max_length=254,
                        verbose_name="Email principal",
                    ),
                ),
                (
                    "contact_email_2",
                    models.EmailField(
                        blank=True,
                        default="kinshasa@aime-rdc.org",
                        max_length=254,
                        verbose_name="Email secondaire",
                    ),
                ),
                (
                    "phone_1",
                    models.CharField(
                        default="+243 844 444 411",
                        max_length=30,
                        verbose_name="Téléphone 1",
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        default="+243 823 090 002",
                        max_length=30,
                        verbose_name="Téléphone 2",
                    ),
                ),
                (
                    "address_1",
                    models.CharField(
                        default="Kinshasa - Gombe",
                        max_length=150,
                        verbose_name="Adresse 1",
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        default="Lubumbashi - Ruashi",
                        max_length=150,
                        verbose_name="Adresse 2",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter / X"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "footer_tagline",
                    models.CharField(
                        default="Organisation dédiée au développement et épanouissement des enfants en RDC.",
                        max_length=250,
                        verbose_name="Slogan footer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
    ]
