# Generated by Django 4.2.14 on 2026-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_herosection_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Accueil"),
                    ("about", "À propos"),
                    ("projects", "Nos Projets"),
                    ("events", "Événements"),
                    ("contact", "Contact"),
                    ("donate", "Faire un don"),
                    ("mbc", "Mutoto Bike Challenge"),
                    ("mbc_registration", "Inscription MBC"),
                    ("msa", "Mutoto Science Adventure"),
                    ("mon_beau_metier", "Mon Beau Métier"),
                    ("manifesto", "Manifeste"),
                    ("impact_theory", "Théorie du Changement"),
                    ("observatory", "Observatoire des Droits"),
                    ("research_center", "Centre de Recherche"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Page",
            ),
        ),
    ]
