# Generated by Django 4.2.14 on 2026-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_herosection_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, verbose_name="Titre"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, verbose_name="URL image (si pas d'upload)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Image galerie (accueil)",
                "verbose_name_plural": "Images galerie (accueil)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="programs/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, verbose_name="URL image (si pas d'upload)"
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Badge — texte"
                    ),
                ),
                (
                    "badge_icon",
                    models.CharField(
                        blank=True,
                        default="fa-star",
                        help_text="Ex: fa-bicycle, fa-flask, fa-briefcase",
                        max_length=40,
                        verbose_name="Badge — icône FontAwesome",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(blank=True, max_length=300, verbose_name="Lien"),
                ),
                (
                    "link_label",
                    models.CharField(
                        default="Découvrir", max_length=60, verbose_name="Lien — texte"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Programme (accueil)",
                "verbose_name_plural": "Programmes (accueil)",
                "ordering": ["order"],
            },
        ),
    ]
