# Generated by Django 4.2.14 on 2026-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_galleryimage_programcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Texte affiché lors du partage (WhatsApp, Facebook...) et pour le référencement.",
                max_length=300,
                verbose_name="Description SEO / partage",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Image affichée lors du partage. Si vide, l'image de fond est utilisée.",
                null=True,
                upload_to="og/",
                verbose_name="Image de partage (Open Graph)",
            ),
        ),
    ]
