# Generated by Django 4.2.14 on 2026-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_herosection_meta_description_herosection_og_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "value",
                    models.PositiveIntegerField(default=0, verbose_name="Valeur"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-heart",
                        help_text="Ex: fa-child, fa-hand-holding-heart, fa-diagram-project, fa-users",
                        max_length=40,
                        verbose_name="Icône FontAwesome",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text='Ex: "≈"',
                        max_length=10,
                        verbose_name="Préfixe",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text='Ex: "+", "K", "FC"',
                        max_length=10,
                        verbose_name="Suffixe",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Statistique d'impact",
                "verbose_name_plural": "Statistiques d'impact",
                "ordering": ["order"],
            },
        ),
    ]
